


export const TYPES = {
    AGREGAR_AL_CARRITO: "AGREGAR_AL_CARRITO",
    ELIMINAR_UN_PRODUCTO: "ELIMINAR_UN_PRODUCTO",
    ELIMINAR_TODOS_LOS_PRODUCTOS: "ELIMINAR_TODOS_LOS_PRODUCTOS",
    LIMPIAR_CARRITO: "LIMPIAR_CARRITO",
}